### ISSUE TITLE
获取了CODE，填入config后，运行main.py报错Object of type PublicInfo is not JSON serializable

### ISSUE THREAD

**Issue by 1098346640** [github123666/cidaren#1]
(kali) D:\test3\cidaren-main>python main.py
[2024-01-02 11:44:03] main INFO: 开始登录
[2024-01-02 11:44:03] main INFO: 初始化公共组件
Traceback (most recent call last):
  File "D:\test3\cidaren-main\main.py", line 169, in <module>
    run()
  File "D:\test3\cidaren-main\main.py", line 113, in run
    get_token(public_info)
  File "D:\test3\cidaren-main\api\login.py", line 30, in get_token
    rsp = requests.rqs3_session.post(basic_url + url, data=json.dumps(data)).json()
  File "C:\Users\lux\.conda\envs\kali\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\lux\.conda\envs\kali\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\lux\.conda\envs\kali\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\lux\.conda\envs\kali\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PublicInfo is not JSON serializable

(kali) D:\test3\cidaren-main>
<img width="938" alt="屏幕截图 2024-01-02 234625" src="https://github.com/github123666/cidaren/assets/51485740/52586181-6be2-4436-a0aa-7e90dace3d86">

**Comment by github123666** [comment]
> (kali) D:\test3\cidaren-main>python main.py [2024-01-02 11:44:03] main INFO: 开始登录 [2024-01-02 11:44:03] main INFO: 初始化公共组件 Traceback (most recent call last): File "D:\test3\cidaren-main\main.py", line 169, in run() File "D:\test3\cidaren-main\main.py", line 113, in run get_token(public_info) File "D:\test3\cidaren-main\api\login.py", line 30, in get_token rsp = requests.rqs3_session.post(basic_url + url, data=json.dumps(data)).json() File "C:\Users\lux.conda\envs\kali\lib\json__init__.py", line 231, in dumps return _default_encoder.encode(obj) File "C:\Users\lux.conda\envs\kali\lib\json\encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "C:\Users\lux.conda\envs\kali\lib\json\encoder.py", line 257, in iterencode return _iterencode(o, 0) File "C:\Users\lux.conda\envs\kali\lib\json\encoder.py", line 179, in default raise TypeError(f'Object of type {o.**class**.**name**} ' TypeError: Object of type PublicInfo is not JSON serializable
> 
> (kali) D:\test3\cidaren-main> <img alt="屏幕截图 2024-01-02 234625" width="938" src="https://private-user-images.githubusercontent.com/51485740/293729073-52586181-6be2-4436-a0aa-7e90dace3d86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTI2MzgsIm5iZiI6MTcwNDIxMjMzOCwicGF0aCI6Ii81MTQ4NTc0MC8yOTM3MjkwNzMtNTI1ODYxODEtNmJlMi00NDM2LWEwYWEtN2U5MGRhY2UzZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhODAyYWY1Zjc1Njg2YjU0MjMxOTY5MDA2MjczYjEzOGNmM2RkYTViOTdhM2YzNDU3ZTFmYjEzMjc0ODhjNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J2RkxTL8nmdgtnweJNlewj8vsfOXSd2cnbDbDwYyCBc">

我脑子抽了，现在可以了。重新拉取一下代码
