### ISSUE TITLE
卡片数据错误，请切换其他卡片学习

### ISSUE THREAD

**Issue by KingPenguinMan** [github123666/cidaren#15]
[2024-04-20 11:29:07] api INFO: 请求有问题{"code":120,"msg":"卡片数据错误，请切换其他卡片学习","data":null,"jv":"0","cv":"0"}退出程序
Stack (most recent call last):
  File "main.py", line 226, in <module>
  File "main.py", line 189, in run
  File "main.py", line 94, in complete_test
  File "main.py", line 142, in complete_practice
  File "answer_questions\answer_questions.py", line 174, in answer
  File "answer_questions\answer_questions.py", line 96, in word_form_mean
  File "api\main_api.py", line 180, in is_self_built
  File "api\main_api.py", line 194, in query_word
  File "api\main_api.py", line 33, in handle_response
Traceback (most recent call last):
  File "main.py", line 226, in <module>
  File "main.py", line 189, in run
  File "main.py", line 94, in complete_test
  File "main.py", line 142, in complete_practice
  File "answer_questions\answer_questions.py", line 174, in answer
  File "answer_questions\answer_questions.py", line 96, in word_form_mean
  File "api\main_api.py", line 180, in is_self_built
  File "api\main_api.py", line 194, in query_word
  File "api\main_api.py", line 34, in handle_response
NameError: name 'exit' is not defined
[15908] Failed to execute script 'main' due to unhandled exception!

**Comment by lihuhuhu** [comment]
> [2024-04-20 11:29:07] api INFO: 请求有问题{"code":120,"msg":"卡片数据错误，请切换其他卡片学习","data":null,"jv":"0","cv":"0"}退出程序 Stack (most recent call last): File "main.py", line 226, in File "main.py", line 189, in run File "main.py", line 94, in complete_test File "main.py", line 142, in complete_practice File "answer_questions\answer_questions.py", line 174, in answer File "answer_questions\answer_questions.py", line 96, in word_form_mean File "api\main_api.py", line 180, in is_self_built File "api\main_api.py", line 194, in query_word File "api\main_api.py", line 33, in handle_response Traceback (most recent call last): File "main.py", line 226, in File "main.py", line 189, in run File "main.py", line 94, in complete_test File "main.py", line 142, in complete_practice File "answer_questions\answer_questions.py", line 174, in answer File "answer_questions\answer_questions.py", line 96, in word_form_mean File "api\main_api.py", line 180, in is_self_built File "api\main_api.py", line 194, in query_word File "api\main_api.py", line 34, in handle_response NameError: name 'exit' is not defined [15908] Failed to execute script 'main' due to unhandled exception!

这个题应该要手动过,应该是那个单词用Spacy模型识别转原型不了,用词达人的接口也转不了原型。后面在更新其他·方法
