### ISSUE TITLE
抓取code，脚本成功获取token后，获取所有单元的信息时报错

### ISSUE THREAD

**Issue by 1098346640** [github123666/cidaren#2]
(kali) D:\test3\cidaren>python main.py
[2024-01-03 12:51:04] main INFO: 开始登录
[2024-01-03 12:51:04] main INFO: 初始化公共组件
[2024-01-03 12:51:05] login INFO: token获取成功ba1ad2f------------af0af688
[2024-01-03 12:51:05] basic_api INFO: 请求成功b'{"code":1,"msg":"success","data":{"menu_list":[],"task_last":null,"task_last_list":[],"user_info":{"id":7940509,"nick_name":"\xe8\x8e\xb1\xe8\xa5\xbf\xef\xbd\x80\xe5\x87\x8c\xe7\x9b\xbe","avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaELEkjG7hwL88tlBOcYBSVDRiaVFp6jf9M9Rj6SavXlXQpsDqu3RHwn1JIovic8POz6thXHiaqajibia6icDJ3zTTCTxeODpvbZSOLdv7PGf1Pm0nPbA/132","mail":null,"student_name":"\xe6\x9d\x8e\xe5\x8a\xb2\xe6\x9d\xbe","student_code":"B23130715","course_id":null,"class_id":218526,"class_name":"B38 ","class_year":2023,"school_id":735,"school_name":"\xe5\x8d\x97\xe4\xba\xac\xe9\x82\xae\xe7\x94\xb5\xe5\xa4\xa7\xe5\xad\xa6","profession":"","admin_class":"","integral_sign":50.0,"integral_study":477.7,"energy_pack":32.5,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1704255162890},"oil_info":{"show_status":2,"hot_show_status":2,"buy_status":2,"contest_code":"d637942ab45122803edd7ed0db35f06e","group_code":""},"contest_info":{"not_start_num":0}},"jv":"0","cv":"0"}'
[2024-01-03 12:51:05] main INFO: 获取所有单元的信息
Traceback (most recent call last):
  File "D:\test3\cidaren\main.py", line 176, in <module>
    run()
  File "D:\test3\cidaren\main.py", line 118, in run
    get_all_unit(public_info)
  File "D:\test3\cidaren\api\basic_api.py", line 33, in get_all_unit
    handle_response(rsp)
  File "D:\test3\cidaren\api\basic_api.py", line 12, in handle_response
    if response.json()['code'] == 1:
KeyError: 'code'
<img width="1137" alt="屏幕截图 2024-01-03 125344" src="https://github.com/github123666/cidaren/assets/51485740/faaa77c8-39f1-41d8-94ec-bc748ae90ea3">

(kali) D:\test3\cidaren>

**Comment by 1098346640** [comment]
basic_api.py中是不是要改成这样：
def handle_response(response):
    code = response.json().get('code')
    if code == 1:
        basic_api.logger.info(f"请求成功{response.content}")
    else:
        basic_api.logger.info(f"请求有问题{response.text}退出程序")
        exit(-1)

**Comment by 1098346640** [comment]
我自己修改后还是报错
(kali) D:\test3\cidaren>python main.py
[2024-01-03 01:10:29] main INFO: 开始登录
[2024-01-03 01:10:29] main INFO: 初始化公共组件
[2024-01-03 01:10:29] basic_api INFO: 请求成功b'{"code":1,"msg":"success","data":{"menu_list":[],"task_last":null,"task_last_list":[],"user_info":{"id":7940509,"nick_name":"\xe8\************x8c\xe7\x9b\xbe","avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaELEkjG7hwL88tlBOcYBSVDRiaVFp6jf9M9Rj6*******1JIovic8POz6thXHiaqajibia6icDJ3zTTCTxeODpvbZSOLdv7PGf1Pm0nPbA/132","mail":null,"student_name":"\xe6\x9d\**************\x9d\xbe","student_code":"B2***********5","course_id":null,"class_id":2***6,"class_name":"B3* ","class_year":2023,"school_id":***5,"school_name":"\xe5\x8d\x******************xa4\xa7\xe5\xad\xa6","profession":"","admin_class":"","integral_sign":50.0,"integral_study":477.7,"energy_pack":32.5,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1704255162890},"oil_info":{"show_status":2,"hot_show_status":2,"buy_status":2,"contest_code":"d637942ab45122803edd7ed0db35f06e","group_code":""},"contest_info":{"not_start_num":0}},"jv":"0","cv":"0"}'
[2024-01-03 01:10:29] main INFO: 获取所有单元的信息
[2024-01-03 01:10:29] basic_api INFO: 请求有问题{"timestamp":"2024-01-03T05:10:29.804+00:00","status":500,"error":"Internal Server Error","message":"","path":"/StudyTask/List"}退出程序

(kali) D:\test3\cidaren>



（* 是我自己加的）

**Comment by github123666** [comment]
> 我自己修改后还是报错 (kali) D:\test3\cidaren>python main.py [2024-01-03 01:10:29] main INFO: 开始登录 [2024-01-03 01:10:29] main INFO: 初始化公共组件 [2024-01-03 01:10:29] basic_api INFO: 请求成功b'{"code":1,"msg":"success","data":{"menu_list":[],"task_last":null,"task_last_list":[],"user_info":{"id":7940509,"nick_name":"\xe8***_x8c\xe7\x9b\xbe","avatar":"[https://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaELEkjG7hwL88tlBOcYBSVDRiaVFp6jf9M9Rj6*******1JIovic8POz6thXHiaqajibia6icDJ3zTTCTxeODpvbZSOLdv7PGf1Pm0nPbA/132","mail":null,"student_name":"\xe6\x9d\**************\x9d\xbe","student_code":"B2***********5","course_id":null,"class_id":2***6,"class_name":"B3](https://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaELEkjG7hwL88tlBOcYBSVDRiaVFp6jf9M9Rj6*******1JIovic8POz6thXHiaqajibia6icDJ3zTTCTxeODpvbZSOLdv7PGf1Pm0nPbA/132%22,%22mail%22:null,%22student_name%22:%22%5Cxe6%5Cx9d%5C**************%5Cx9d%5Cxbe%22,%22student_code%22:%22B2***********5%22,%22course_id%22:null,%22class_id%22:2***6,%22class_name%22:%22B3)_ ","class_year":2023,"school_id":_**5,"school_name":"\xe5\x8d\x**_*******xa4\xa7\xe5\xad\xa6","profession":"","admin_class":"","integral_sign":50.0,"integral_study":477.7,"energy_pack":32.5,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1704255162890},"oil_info":{"show_status":2,"hot_show_status":2,"buy_status":2,"contest_code":"d637942ab45122803edd7ed0db35f06e","group_code":""},"contest_info":{"not_start_num":0}},"jv":"0","cv":"0"}' [2024-01-03 01:10:29] main INFO: 获取所有单元的信息 [2024-01-03 01:10:29] basic_api INFO: 请求有问题{"timestamp":"2024-01-03T05:10:29.804+00:00","status":500,"error":"Internal Server Error","message":"","path":"/StudyTask/List"}退出程序
> 
> (kali) D:\test3\cidaren>
> 
> （* 是我自己加的）

你自学任务是不是没选书

**Comment by github123666** [comment]
> > 我自己修改后还是报错 (kali) D:\test3\cidaren>python main.py [2024-01-03 01:10:29] main INFO: 开始登录 [2024-01-03 01:10:29] main INFO: 初始化公共组件 [2024-01-03 01:10:29] basic_api INFO: 请求成功b'{"code":1,"msg":"success","data":{"menu_list":[],"task_last":null,"task_last_list":[],"user_info":{"id":7940509,"nick_name":"\xe8***_x8c\xe7\x9b\xbe","avatar":"[https://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaELEkjG7hwL88tlBOcYBSVDRiaVFp6jf9M9Rj6_**1JIovic8POz6thXHiaqajibia6icDJ3zTTCTxeODpvbZSOLdv7PGf1Pm0nPbA/132","mail":null,"student_name":"\xe6\x9d***_******\x9d\xbe","student_code":"B2********_**5","course_id":null,"class_id":2**_6,"class_name":"B3](https://thirdwx.qlogo.cn/mmopen/vi_32/PiajxSqBRaELEkjG7hwL88tlBOcYBSVDRiaVFp6jf9M9Rj6*******1JIovic8POz6thXHiaqajibia6icDJ3zTTCTxeODpvbZSOLdv7PGf1Pm0nPbA/132%22,%22mail%22:null,%22student_name%22:%22%5Cxe6%5Cx9d%5C**************%5Cx9d%5Cxbe%22,%22student_code%22:%22B2***********5%22,%22course_id%22:null,%22class_id%22:2***6,%22class_name%22:%22B3)_ ","class_year":2023,"school_id":_**5,"school_name":"\xe5\x8d\x**_*******xa4\xa7\xe5\xad\xa6","profession":"","admin_class":"","integral_sign":50.0,"integral_study":477.7,"energy_pack":32.5,"member_state":2,"member_time_course":0,"auto_answer_state":1,"auto_answer_time":1000,"wx_msg_status":1,"update_time":1704255162890},"oil_info":{"show_status":2,"hot_show_status":2,"buy_status":2,"contest_code":"d637942ab45122803edd7ed0db35f06e","group_code":""},"contest_info":{"not_start_num":0}},"jv":"0","cv":"0"}' [2024-01-03 01:10:29] main INFO: 获取所有单元的信息 [2024-01-03 01:10:29] basic_api INFO: 请求有问题{"timestamp":"2024-01-03T05:10:29.804+00:00","status":500,"error":"Internal Server Error","message":"","path":"/StudyTask/List"}退出程序
> > (kali) D:\test3\cidaren>
> > （* 是我自己加的）
> 
> 你自学任务是不是没选书
![image](https://github.com/github123666/cidaren/assets/76271031/9c87ead8-f8b3-443b-9657-91a2615d9187)
现在只支持自学任务,班级任务还没开始写(应该也是大同小异)

**Comment by 1098346640** [comment]
是的，我们直接布置的班级任务，班级任务里的测试任务，这玩意算平时分，所以打算脚步来提高正确率。

**Comment by 1098346640** [comment]
![Screenshot_2024-01-03-13-42-38-582_com.tencent.mm.jpg](https://github.com/github123666/cidaren/assets/51485740/09248df0-bf5d-44ab-85fd-a5ea2bd0b314)

就这种

**Comment by github123666** [comment]
> ![Screenshot_2024-01-03-13-42-38-582_com.tencent.mm.jpg](https://private-user-images.githubusercontent.com/51485740/293840968-09248df0-bf5d-44ab-85fd-a5ea2bd0b314.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODEwNjIsIm5iZiI6MTcwNDI4MDc2MiwicGF0aCI6Ii81MTQ4NTc0MC8yOTM4NDA5NjgtMDkyNDhkZjAtYmY1ZC00NGFiLTg1ZmQtYTVlYTJiZDBiMzE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDExMTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjhkNWNjNTEyNTllYjcwMzk0NzQxZDY5NmMxZTdiNzc5ZDc4ZWE5MDViNGVlNmVmNzQyYWE3ZmE2MjcwYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fhfb9XfSHyXZfiosz-s5xJp0v52yPdU1nXDpz_KknD0)
> 
> 就这种

昨天刷了1000分,今天账号被风控了(切换不了班级),改天在添加过班级任务吧！
