### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by jfnice** [github123666/cidaren#20]
C:\Users\jfnic>C:\Users\jfnic\Desktop\main\github123666.exe
[2024-05-20 03:05:29] main INFO: 开始登录
[2024-05-20 03:05:29] main INFO: 侵权请联系删除
[2024-05-20 03:05:29] main INFO: github123666 <- github.com
[2024-05-20 03:05:29] main INFO: 初始化公共组件
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app.vocabgo.com', port=443): Max retries exceeded with url: /student/api/Student/Main?timestamp=1716188729521&version=2.6.1.231204&app_type=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 226, in <module>
  File "main.py", line 170, in run
  File "main.py", line 159, in init_token
  File "api\login.py", line 47, in verify_token
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='app.vocabgo.com', port=443): Max retries exceeded with url: /student/api/Student/Main?timestamp=1716188729521&version=2.6.1.231204&app_type=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
[22652] Failed to execute script 'main' due to unhandled exception!

**Comment by lihuhuhu** [comment]
> C:\Users\jfnic>C:\Users\jfnic\Desktop\main\github123666.exe [2024-05-20 03:05:29] main INFO: 开始登录 [2024-05-20 03:05:29] main INFO: 侵权请联系删除 [2024-05-20 03:05:29] main INFO: github123666 <- github.com [2024-05-20 03:05:29] main INFO: 初始化公共组件 urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "requests\adapters.py", line 486, in send File "urllib3\connectionpool.py", line 844, in urlopen File "urllib3\util\retry.py", line 515, in increment urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app.vocabgo.com', port=443): Max retries exceeded with url: /student/api/Student/Main?timestamp=1716188729521&version=2.6.1.231204&app_type=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main.py", line 226, in File "main.py", line 170, in run File "main.py", line 159, in init_token File "api\login.py", line 47, in verify_token File "requests\sessions.py", line 602, in get File "requests\sessions.py", line 589, in request File "requests\sessions.py", line 703, in send File "requests\adapters.py", line 517, in send requests.exceptions.SSLError: HTTPSConnectionPool(host='app.vocabgo.com', port=443): Max retries exceeded with url: /student/api/Student/Main?timestamp=1716188729521&version=2.6.1.231204&app_type=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) [22652] Failed to execute script 'main' due to unhandled exception!

梯子关了
