### ISSUE TITLE
求修复 binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by ResortAnthem** [github123666/cidaren#28]
Traceback (most recent call last):
  File "main.py", line 226, in <module>
  File "main.py", line 206, in run
  File "main.py", line 142, in complete_practice
  File "answer_questions\answer_questions.py", line 174, in answer
  File "answer_questions\answer_questions.py", line 96, in word_form_mean
  File "api\main_api.py", line 180, in is_self_built
  File "api\main_api.py", line 196, in query_word
  File "decryptencrypt\debase64.py", line 9, in debase64
  File "base64.py", line 87, in b64decode
binascii.Error: Incorrect padding
[21768] Failed to execute script 'main' due to unhandled exception!

**Comment by lihuhuhu** [comment]
看最新的issues

**Comment by ResortAnthem** [comment]
> 看最新的issues

感谢维护
