### ISSUE TITLE
自学任务好像存在一些问题

### ISSUE THREAD

**Issue by XPIPI-N3V3R** [github123666/cidaren#4]
有可能是我配置出问题了？
`[2024-02-27 11:26:19] main INFO: 处理words
[2024-02-27 11:26:19] main INFO: 选择该单元所有单词
[2024-02-27 11:26:19] api INFO: 勾选全部单词并提交
[2024-02-27 11:26:19] api INFO: 请求有问题{"code":0,"msg":"对不起，存在小节任务未完成，请先完成小节任务","data":null,"jv":"0","cv":"0"}退出程序
Stack (most recent call last):
  File "main.py", line 172, in <module>
  File "main.py", line 153, in run
  File "main.py", line 79, in complete_practice
  File "api\main_api.py", line 60, in select_all_word
  File "api\main_api.py", line 32, in handle_response
Traceback (most recent call last):
  File "main.py", line 172, in <module>
  File "main.py", line 153, in run
  File "main.py", line 79, in complete_practice
  File "api\main_api.py", line 60, in select_all_word
  File "api\main_api.py", line 33, in handle_response
NameError: name 'exit' is not defined
[100] Failed to execute script 'main' due to unhandled exception!`

**Comment by github123666** [comment]
> 有可能是我配置出问题了？ `[2024-02-27 11:26:19] main INFO: 处理words [2024-02-27 11:26:19] main INFO: 选择该单元所有单词 [2024-02-27 11:26:19] api INFO: 勾选全部单词并提交 [2024-02-27 11:26:19] api INFO: 请求有问题{"code":0,"msg":"对不起，存在小节任务未完成，请先完成小节任务","data":null,"jv":"0","cv":"0"}退出程序 Stack (most recent call last): File "main.py", line 172, in <module> File "main.py", line 153, in run File "main.py", line 79, in complete_practice File "api\main_api.py", line 60, in select_all_word File "api\main_api.py", line 32, in handle_response Traceback (most recent call last): File "main.py", line 172, in <module> File "main.py", line 153, in run File "main.py", line 79, in complete_practice File "api\main_api.py", line 60, in select_all_word File "api\main_api.py", line 33, in handle_response NameError: name 'exit' is not defined [100] Failed to execute script 'main' due to unhandled exception!`

已解决
